### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [vmxdev/tkvdb#2]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [tkvdb_close](https://github.com/vmxdev/tkvdb/blob/e5622ccf77d1c7183959492e01490260a65ac78c/tkvdb.c#L357 "tkvdb_close function")
- [tkvdb_cursor_free](https://github.com/vmxdev/tkvdb/blob/e5622ccf77d1c7183959492e01490260a65ac78c/tkvdb.c#L419 "tkvdb_cursor_free function")

**Comment by vmxdev** [comment]
Ok, fixed, thank you

**Comment by elfring** [comment]
[A few update candidates were left over](https://github.com/vmxdev/tkvdb/blob/380036fdfc3dfc93e17018acb8b8cacedca7c234/tkvdb.c#L502 "Update candidate: tkvdb_cursor_reset()").

**Comment by vmxdev** [comment]
Looks like all occurrences are fixed now. Thank you again

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/vmxdev/tkvdb/commit/77ca8a3f49abcc809a7a2a012330e39b982bd6a0 "Remove unnecessary null pointer checks").
