### ISSUE TITLE
Improve cooperation with C++ environments

### ISSUE THREAD

**Issue by elfring** [vmxdev/tkvdb#4]
[Some code from C source files](https://github.com/vmxdev/tkvdb/blob/7a5f77a87389e039fca6a19b089b87ccb1b97b6c/tkvdb.h#L8 "Update candidate") should be wrapped by the setting “[`extern "C"`](https://isocpp.org/wiki/faq/mixing-c-and-cpp#include-c-hdrs-personal "How can I modify my own C header files so it’s easier to #include them in C++ code?")” for C++ tools.

**Comment by vmxdev** [comment]
Is there a need for use “extern "C"”  with typedefs? Functions are already wrapped with it.
Test C++ code (with g++) compiled and linked without any warnings.

**Comment by elfring** [comment]
Can it be nicer to put such an annotation at the top of your C header file (so that more declarations can be safely handled also for C++)?
