### ISSUE TITLE
Iterate in memcmp order?

### ISSUE THREAD

**Issue by canadaduane** [vmxdev/tkvdb#8]
Is there a way to iterate over keys in order?

**Comment by canadaduane** [comment]
Ahh, I just realized the iteration does occur in memcmp order. What I'm looking for is iterating over values in order. Possible?

**Comment by vmxdev** [comment]
No, it's not possible directly.

You can build secondary index manually, using values as keys. I guess you need to order by uint64_t. It can be a bit tricky. Integers for correct sorting with radix tree must be in big-endian (or network) byte order. So you may use htobe64 (or something like this for your OS) before storing key and be64toh after retrieve to convert it back to host byte order.

Main database

| Key  | Value |
| ------------- | ------------- |
| valA  | 2 (host byte order, most probably little-endian)  |
| valB  | 1  |
| ...  | ...  |

Additional database with secondary index

| Key  | Value |
| ------------- | ------------- |
| 0x0000000000000001 (big-endian)  | valB  |
| 0x0000000000000002  | valA  |
| ...  | ...  |


Depending on your needs you can build secondary index right before using it or update on the fly, after each key-value pair change.

Though it may looks complicated, we have no plans to support secondary indexes in another way.

**Comment by canadaduane** [comment]
Thanks, this is a good way to make it work. I may punt on it for now, but
it's good to know it's possible to pull this tool out again later.
